# Generated by Django 4.2.24 on 2026-06-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_athletes", models.IntegerField(default=0)),
                ("active_memberships", models.IntegerField(default=0)),
                ("expired_memberships", models.IntegerField(default=0)),
                ("expiring_soon", models.IntegerField(default=0)),
                ("new_this_month", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Dashboard stats",
            },
        ),
    ]
