# Generated by Django 4.2.24 on 2026-06-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardStats",
        ),
    ]
