# Generated by Django 4.2.30 on 2026-06-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name_ar", models.CharField(max_length=100)),
                ("initials", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("profile_image", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["full_name_ar"],
            },
        ),
        migrations.CreateModel(
            name="TrainerClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("intensity", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="LYD", max_length=10)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("image_url", models.URLField(blank=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="trainers.trainer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trainer classes",
                "ordering": ["title"],
            },
        ),
    ]
