# Generated by Django 4.2.30 on 2026-06-26 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0002_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="trainerreview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
