# Generated by Django 4.2.24 on 2026-07-05 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0004_add_bank_account_fields"),
        ("trainers", "0003_alter_trainer_rating_alter_trainerreview_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainers",
                to="departments.department",
            ),
        ),
    ]
