# Generated by Django 4.2.30 on 2026-06-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0002_alter_athlete_created_at_alter_athlete_full_name_and_more"),
        ("notifications", "0003_alter_notification_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteAdminProxy",
            fields=[],
            options={
                "verbose_name": "Athlete WhatsApp",
                "verbose_name_plural": "Athlete WhatsApp",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("athletes.athlete",),
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(blank=True, max_length=100)),
                ("message_body", models.TextField()),
                ("recipient_phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("whatsapp_message_id", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="athletes.athlete",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Message",
                "verbose_name_plural": "WhatsApp Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
