# Generated by Django 4.2.30 on 2026-06-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="is_locked",
        ),
        migrations.AddField(
            model_name="achievement",
            name="status",
            field=models.CharField(
                choices=[
                    ("locked", "Locked"),
                    ("unlocked", "Unlocked"),
                    ("completed", "Completed"),
                ],
                default="locked",
                max_length=20,
            ),
        ),
    ]
