# Generated by Django 4.2.24 on 2026-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_days", models.PositiveIntegerField()),
                ("features", models.JSONField(blank=True, default=list)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for frontend",
                        max_length=100,
                    ),
                ),
                (
                    "color_class",
                    models.CharField(
                        blank=True,
                        help_text="Tailwind or CSS class for styling",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Subscription Package",
                "verbose_name_plural": "Subscription Packages",
                "ordering": ["order"],
            },
        ),
    ]
