# Generated by Django 4.2.24 on 2026-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_init"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionpackage",
            name="duration_days",
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="duration_type",
            field=models.CharField(
                choices=[("weeks", "Weeks"), ("months", "Months")],
                default="months",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="duration_value",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of weeks or months"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="max_athletes",
            field=models.PositiveIntegerField(
                default=1, help_text="Max athletes allowed for this package"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="tag",
            field=models.CharField(
                choices=[
                    ("discount", "Discount"),
                    ("special", "Special"),
                    ("normal", "Normal"),
                ],
                db_index=True,
                default="normal",
                max_length=10,
            ),
        ),
    ]
