# Generated by Django 4.2.30 on 2026-06-30 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0004_add_bank_account_fields"),
        ("packages", "0002_remove_subscriptionpackage_duration_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpackage",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Academy this package belongs to. Null = available to all academies.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="departments.department",
            ),
        ),
    ]
