# Generated by Django 4.2.27 on 2026-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0003_subscriptionpackage_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpackage",
            name="new_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="First-time subscription price",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("multi_month", "Multi-Month"),
                    ("single_session", "Single Session (حصة)"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="renewal_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Renewal subscription price",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpackage",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base/New price for backward compatibility",
                max_digits=10,
            ),
        ),
    ]
