# Generated by Django 4.2.27 on 2026-08-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_subscriptionpackage_new_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpackage",
            name="duration_type",
            field=models.CharField(
                choices=[("days", "Days"), ("weeks", "Weeks"), ("months", "Months")],
                default="months",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpackage",
            name="duration_value",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of days, weeks or months"
            ),
        ),
    ]
