# Generated by Django 4.2.30 on 2026-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="package_name",
            field=models.CharField(default="الباقة الأساسية", max_length=100),
        ),
    ]
