# Generated by Django 4.2.30 on 2026-06-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_init"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("pending", "Pending"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
