# Generated by Django 4.2.24 on 2026-06-28 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_sport_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0004_alter_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="departments.group",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="invoice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank_transfer", "Bank Transfer")],
                default="cash",
                max_length=20,
            ),
        ),
    ]
