# Generated by Django 4.2.30 on 2026-06-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0005_subscription_approved_at_subscription_approved_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
