# Generated by Django 4.2.24 on 2026-07-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_alter_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
