# Generated by Django 4.2.27 on 2026-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_subscription_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="shift_name",
            field=models.CharField(
                blank=True, default="", help_text="اسم الفترة المختارة", max_length=100
            ),
        ),
    ]
