# Generated by Django 4.2.27 on 2026-08-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscription_shift_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="renewal",
            name="invoice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="renewals/"),
        ),
        migrations.AddField(
            model_name="renewal",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank_transfer", "Bank Transfer")],
                default="cash",
                max_length=20,
            ),
        ),
    ]
