# Generated by Django 4.2.24 on 2026-06-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0003_registrationrequest_athlete_registration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parentathlete",
            options={"ordering": ["-created_at"]},
        ),
    ]
