# Generated by Django 4.2.24 on 2026-07-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0004_alter_parentathlete_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequest",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
