# Generated by Django 4.2.27 on 2026-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0005_registrationrequest_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="health_status",
            field=models.TextField(
                blank=True, default="", help_text="الحالة الصحية / ملاحظات طبية"
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="parent_name",
            field=models.CharField(
                blank=True, default="", help_text="اسم ولي الأمر", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="residence",
            field=models.CharField(
                blank=True, default="", help_text="السكن / العنوان", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="health_status",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="residence",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="athlete",
            name="parent_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
