# Generated by Django 4.2.27 on 2026-07-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0005_group_shifts"),
        ("athletes", "0006_athlete_health_status_athlete_parent_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="athletes",
                to="departments.sport",
            ),
        ),
    ]
