# Generated by Django 4.2.24 on 2026-06-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_athlete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("reception", "Reception Staff"),
                    ("trainer", "Trainer"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
