# Generated by Django 4.2.30 on 2026-06-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0004_add_bank_account_fields"),
        ("accounts", "0006_add_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managers",
                to="departments.department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("reception", "Reception Staff"),
                    ("academy_manager", "Academy Manager"),
                    ("trainer", "Trainer"),
                    ("athlete", "Athlete"),
                    ("parent", "Parent"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
