# Generated by Django 4.2.27 on 2026-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_academy_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="residence",
            field=models.CharField(
                blank=True, default="", help_text="السكن / العنوان", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_phone",
            field=models.CharField(
                blank=True, default="", help_text="رقم الواتساب", max_length=20
            ),
        ),
    ]
