# Generated by Django 4.2.27 on 2026-07-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_residence_user_whatsapp_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("reception", "Reception Staff"),
                    ("academy_manager", "Academy Manager"),
                    ("special_manager", "Special Manager"),
                    ("trainer", "Trainer"),
                    ("athlete", "Athlete"),
                    ("parent", "Parent"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
