# Generated by Django 4.2.27 on 2026-07-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0005_group_shifts"),
        ("accounts", "0009_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_by_users",
                to="departments.sport",
            ),
        ),
    ]
