# Generated by Django 4.2.30 on 2026-06-26 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="color",
            field=models.CharField(
                default="#1487D4",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$", "Enter a valid hex color"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="departments/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_ar",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
