# Generated by Django 4.2.24 on 2026-06-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_sport_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="bank_account_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="department",
            name="iban",
            field=models.CharField(blank=True, default="", max_length=34),
        ),
    ]
