# Generated by Django 4.2.27 on 2026-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0004_add_bank_account_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="shifts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of shifts e.g. [{'name': 'الفترة الأولى', 'start_time': '14:00', 'end_time': '15:00'}]",
            ),
        ),
    ]
